version: "3.7"

services:
    db-server:
        container_name: db-server
        build: ./db_server
        networks:
            - backend
        environment:
            - MYSQL_ROOT_PASSWORD=JustDance2018
            - MYSQL_DATABASE:${DB_NAME}
            - MYSQL_USER:${DB_USER}
            - MYSQL_PASSWORD:${DB_PASS}
    
    app-server:
        container_name: app-server
        build: ./app_server
        networks:
            - frontend
            - backend
        depends_on:
            - db-server
        volumes:
            - type: bind
              source: ./app_server/fashionDays
              target: /var/www/html/fashionDays
        environment:
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
        ports:
            - "8088:80"
        command: node /var/www/html/fashionDays/server.js
    
    static-content:
        container_name: static-content
        build: ./static_content
        networks:
            - frontend
        volumes:
          - type: bind
            source: ./static_content/fashionDays
            target: /usr/local/apache2/htdocs/fashionDays
        ports:
            - "8080:80"
      
networks:
  frontend:
  backend:
