version: "3.7"

services:
    fashion-db-server:
        container_name: fashion-db-server
        build: ./db_server
        networks:
            - backend
        environment:
            - MYSQL_ROOT_PASSWORD=JustDance2018
            - MYSQL_DATABASE:${DB_NAME}
            - MYSQL_USER:${DB_USER}
            - MYSQL_PASSWORD:${DB_PASS}
    
    fashion-app-server:
        container_name: fashion-app-server
        build: ./app_server
        networks:
            - frontend
            - backend
        depends_on:
            - fashion-db-server
        volumes:
            - type: bind
              source: ./app_server/fashionDays
              target: /var/www/html/fashionDays
        environment:
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
        ports:
            - "8090:80"
        command: node /var/www/html/fashionDays/server.js
    
    fashion-static-content:
        container_name: fashion-static-content
        build: ./static_content
        networks:
            - frontend
        volumes:
          - type: bind
            source: ./static_content/fashionDays
            target: /usr/local/apache2/htdocs/fashionDays
        ports:
            - "8091:80"
      
networks:
  frontend:
  backend:
